services:
  - type: web
    name: dwg-visor
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: APS_CLIENT_ID
        sync: false
      - key: APS_CLIENT_SECRET
        sync: false
      - key: APS_BUCKET
        value: ""
