services:
  - type: web
    name: dwg-buscador-web
    runtime: docker
    plan: free
    envVars:
      - key: APS_CLIENT_ID
        sync: false
      - key: APS_CLIENT_SECRET
        sync: false
      - key: APS_BUCKET
        sync: false
